//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeckinUmurControl.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ayarlars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ayarlars()
        {
            this.Kullanicilars = new HashSet<Kullanicilars>();
        }
    
        public int AyarlarID { get; set; }
        public int KullanicilarID { get; set; }
        public int DiskSiniri { get; set; }
        public string UyelikTipi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kullanicilars> Kullanicilars { get; set; }
    }
}
