//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeckinUmurControl.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChoiceDrives
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChoiceDrives()
        {
            this.GelenMesajlars = new HashSet<GelenMesajlars>();
            this.GidenMesajlars = new HashSet<GidenMesajlars>();
        }
    
        public int ChoiceDriveID { get; set; }
        public string Konumu { get; set; }
        public bool Silindimi { get; set; }
        public bool Paylasimdami { get; set; }
        public int KullanicilarID { get; set; }
        public string Tarih { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GelenMesajlars> GelenMesajlars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GidenMesajlars> GidenMesajlars { get; set; }
    }
}
