//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeckinUmurControl.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GelenMesajlars
    {
        public int GelenMesajlarID { get; set; }
        public string Mesaj { get; set; }
        public bool Okundumu { get; set; }
        public bool Silindimi { get; set; }
        public int MesajKlasoruID { get; set; }
        public int KullanicilarID { get; set; }
        public int Gonderen { get; set; }
        public string Tarih { get; set; }
        public int ChoiceDriveID { get; set; }
    
        public virtual ChoiceDrives ChoiceDrives { get; set; }
        public virtual Kullanicilars Kullanicilars { get; set; }
        public virtual MesajKlasorus MesajKlasorus { get; set; }
    }
}
