//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeckinUmurControl.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanicilars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kullanicilars()
        {
            this.GelenMesajlars = new HashSet<GelenMesajlars>();
            this.GidenMesajlars = new HashSet<GidenMesajlars>();
        }
    
        public int KullanicilarID { get; set; }
        public string Adi { get; set; }
        public string Sifresi { get; set; }
        public string Yetkisi { get; set; }
        public string ProfilResmi { get; set; }
        public bool Aktifmi { get; set; }
        public string EklenmeTarihi { get; set; }
        public bool Online { get; set; }
        public int AyarlarID { get; set; }
    
        public virtual Ayarlars Ayarlars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GelenMesajlars> GelenMesajlars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GidenMesajlars> GidenMesajlars { get; set; }
    }
}
