//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeckinUmurControl.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class seckinumurEntities : DbContext
    {
        public seckinumurEntities()
            : base("name=seckinumurEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ayarlars> Ayarlars { get; set; }
        public virtual DbSet<ChoiceDrives> ChoiceDrives { get; set; }
        public virtual DbSet<GelenMesajlars> GelenMesajlars { get; set; }
        public virtual DbSet<GidenMesajlars> GidenMesajlars { get; set; }
        public virtual DbSet<Kullanicilars> Kullanicilars { get; set; }
        public virtual DbSet<MesajKlasorus> MesajKlasorus { get; set; }
    }
}
